// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDdl84NkQq1scoSKmWv3MtMBUweA2yHs',
    appId: '1:684785925677:web:cc1440a58e62fe580282a4',
    messagingSenderId: '684785925677',
    projectId: 'projek-distro',
    authDomain: 'projek-distro.firebaseapp.com',
    storageBucket: 'projek-distro.firebasestorage.app',
    measurementId: 'G-DJHX1GVWB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3kEIs9vTZ3uh0sYnmf6TyLhUY3cNOsME',
    appId: '1:684785925677:android:d149da9995d7c7350282a4',
    messagingSenderId: '684785925677',
    projectId: 'projek-distro',
    storageBucket: 'projek-distro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLNTvqeoX531JOIH2hLgArHiadmzqbRoU',
    appId: '1:684785925677:ios:e7701e844accd5170282a4',
    messagingSenderId: '684785925677',
    projectId: 'projek-distro',
    storageBucket: 'projek-distro.firebasestorage.app',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLNTvqeoX531JOIH2hLgArHiadmzqbRoU',
    appId: '1:684785925677:ios:e7701e844accd5170282a4',
    messagingSenderId: '684785925677',
    projectId: 'projek-distro',
    storageBucket: 'projek-distro.firebasestorage.app',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFDdl84NkQq1scoSKmWv3MtMBUweA2yHs',
    appId: '1:684785925677:web:ce3fe37f2f1f27810282a4',
    messagingSenderId: '684785925677',
    projectId: 'projek-distro',
    authDomain: 'projek-distro.firebaseapp.com',
    storageBucket: 'projek-distro.firebasestorage.app',
    measurementId: 'G-343KDE6Q2W',
  );
}
